---
- name: provision db for sparta app
  hosts: db
  remote_user: vagrant
  become_method: sudo
  become_user: root
  become: yes

  tasks:
  - name: update sources
    apt:
      update_cache: yes

  - name: make mongodb sources list for apt
    file:
      path: /etc/apt/sources.list.d/mongodb-org-4.2.list
      state: touch

  - name: attaining package key
    # become_user: root
    # command: sudo touch /etc/apt/sources.list.d/mongodb-org-4.2.list
    # command: wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-4.2.asc
      state: present


  - name: adding mongo version to sources list
    become_user: root
    shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list

  # - name: installing mongo
  #   command: sudo apt-get update
  #   command: sudo apt-get install -y mongodb-org --allow-unauthenticated

  - name: installing mongo
    apt:
      name: mongodb-org
      update_cache: yes


  - name: config template link
    template:
      src: mongod.conf
      dest: /etc/mongod.conf
      mode: 0777
    notify:
      - restart mongodb

  - name: start and enable mongodb
    service:
      name: mongodb
      enabled: yes
    service:
      name: mongodb
      state: started

  handlers:
  - name: restart mongodb
    service:
      name: mongodb
      state: restarted
