---
- name: provision sparta app
  hosts: app
  remote_user: vagrant
  become_method: sudo
  become_user: root
  become: yes

  tasks:

  - name: update sources
    apt:
      update_cache: yes

  - name: install nginx and npm
    apt:
      pkg:
        - nginx
        - npm
      state: latest

  - name: start and enable nginx
    service:
      name: nginx
      state: started
    service:
      name: nginx
      enabled: yes

  - name: config template link
    template:
      src: proxy.conf.erb
      dest: /etc/nginx/sites-available/proxy.conf
      mode: 0777
    notify:
      - restart nginx

  - name: resource link / sites files in machine
    file:
      src: /etc/nginx/sites-enabled/proxy.conf
      dest: /etc/nginx/sites-available/proxy.conf
      state: link
      force: yes
    notify:
      - restart nginx

  - name: delete default file
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify:
      - restart nginx

- name: install nodejs
    # become_user: root
    # command: apt-get install nodejs -y
    apt:
      name: nodejs
      state: latest
  
  - name: install pm2
    npm:
      name: pm2
      global: yes
      state: present

- name: install app dependancies via npm
    become_user: root
    block:

      - name: checking existing sym link
        stat:
          path: /usr/bin/node
        register: links

      - name: create sym link for node
        command: ln -s /usr/bin/nodejs /usr/bin/node
        when: links is failed
         -
      - name: cd into app home directory
        command: cd /home/ubuntu/app/
      - name: install app dependancies
        command: npm install

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
